name: "Label commenter"

on:
  issues:
    types:
      - "labeled"
      - "unlabeled"

permissions:
  contents: "read"
  issues: "write"

jobs:
  comment:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Label commenter"
        uses: "peaceiris/actions-label-commenter@v1"
